name: Smart Mom Business Plan Webhook

on:
  issues:
    types: [opened]

# ADD THIS SECTION - GitHub Actions Permissions
permissions:
  issues: write
  contents: read

jobs:
  process-submission:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'smart-mom-submission')
    
    steps:
    - name: Process Smart Mom Submission
      uses: actions/github-script@v6
      with:
        script: |
          # Your existing script here...
